name: Weekly Firmware Build

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Building ${{ matrix.file }} / ESPHome ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - Integrations/ESPHome/TEMP-1.yaml
          - Integrations/ESPHome/TEMP-1_BLE.yaml
          - Integrations/ESPHome/TEMP-1B.yaml
          - Integrations/ESPHome/TEMP-1B_BLE.yaml
          - Integrations/ESPHome/TEMP-1_Minimal.yaml
          - Integrations/ESPHome/TEMP-1B_Minimal.yaml

          - Integrations/ESPHome/TEMP-1_R2.yaml
          - Integrations/ESPHome/TEMP-1_BLE_R2.yaml
          - Integrations/ESPHome/TEMP-1B_R2.yaml
          - Integrations/ESPHome/TEMP-1B_BLE_R2.yaml
          - Integrations/ESPHome/TEMP-1_Minimal_R2.yaml
          - Integrations/ESPHome/TEMP-1B_Minimal_R2.yaml
        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6.0.2
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ matrix.file }}